### PR TITLE
Allow setting theme options

### LINKED ISSUE #11: Theme configuration object
**Describe the problem**

When using a built in theme, we cannot pass a configuration object. this makes it impossible to change the direction of the overlay theme easely.

**Describe the proposed solution**

adding a themeConfig object that can be passed to the `new SwupOverlayTheme()` class, like so :

```js
SwupOverlayTheme({
  direction: 'to-right'
});
```

**How important is this feature to you?**

- [ ] Nice to have
- [x] Would make my life a lot easier
- [ ] I cannot use swup without it

### PR DESCRIPTION
**Pull request by daun**
**Description**

Allow passing in theme options as second argument:

```js
{
  theme: ['overlay', { direction: 'to-right' }]
}
```

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [ ] ~~All tests are passing (`npm run test`)~~
- [ ] ~~New or updated tests are included~~
- [x] The documentation was updated as required

**Additional information**

Closes #11

### CODE REVIEW

**Comment by hirasso** [comment]
Why did you decide for the array form? I think I'd prefer a more explicit object like

```js
{
  name: string,
  options: object
}
```

**Comment by daun** [comment]
@hirasso Mostly to keep it compact. I spent so much time in ESLint configs lately where the format of tuples for config also just felt natural: 

```
"no-undef": ["error", { "typeof": true }]
```

Your suggestion is valid as well and is actually what I had implemented at some point. What bothered me about it was that customizing a single theme option would turn a single line into seven lines if formatted normally. That's just a lot of visual noise, I felt like.

```js
{
  // Before
  theme: 'overlay',

  // After
  theme: {
    name: 'overlay',
    options: {
      direction: 'to-right
    }
  },

  // Versus
  theme: ['overlay', { direction: 'to-right' }]
}
```

**Comment by hirasso** [comment]
It's probably a matter of taste. I prefer clarity over density most of the time.

**Comment by daun** [comment]
@hirasso Definitely. If the thought of a tuple for this makes you shudder, feel free to push to this branch and I'll happily accept it. While I have a strong preference for it in this single case, I'm not opposed to the object version either.

**Review by hirasso — APPROVED** [review]

**Comment by hirasso** [comment]
If you feel strongly about it, lets go with it.

**Pull request merged**
